/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressBook: typeof import('./src/components/frontend/AddressBook.vue')['default']
    AddressForm: typeof import('./src/components/frontend/AddressForm.vue')['default']
    AddressPanel: typeof import('./src/components/frontend/AddressPanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTextarea: typeof import('element-plus/es')['ElTextarea']
    FormItem: typeof import('./src/components/frontend/FormItem.vue')['default']
    Header: typeof import('./src/components/shared/Header.vue')['default']
    Login: typeof import('./src/components/shared/Login.vue')['default']
    MapContainner: typeof import('./src/components/shared/MapContainner.vue')['default']
    Register: typeof import('./src/components/shared/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTable: typeof import('./src/components/frontend/SearchTable.vue')['default']
    Sidebar: typeof import('./src/components/shared/Sidebar.vue')['default']
    TitleBox: typeof import('./src/components/shared/TitleBox.vue')['default']
  }
}
